apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: mwe4tnf3l-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/mwe4tnf3l-java-springboot-gitops